import {NgModule} from '@angular/core';
import {
  MatAutocompleteModule,
  MatButtonModule,
  MatCardModule,
  MatDatepickerModule,
  MatDialogModule,
  MatExpansionModule,
  MatFormFieldModule,
  MatGridListModule,
  MatIconModule,
  MatInputModule,
  MatMenuModule,
  MatRippleModule,
  MatSidenavModule,
  MatSliderModule,
  MatTooltipModule,
  MatSnackBarModule,
  MatListModule,
  MatSelectModule,
  MatCheckboxModule,
  MatToolbarModule,
  MatTabsModule,
  MatTableModule,
  MatPaginatorModule
} from '@angular/material';

import {FormsModule, ReactiveFormsModule} from '@angular/forms';


@NgModule({
  imports: [
    MatCardModule,
    MatButtonModule,
    MatGridListModule,
    MatMenuModule,
    MatIconModule,
    MatSidenavModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatExpansionModule,
    FormsModule,
    ReactiveFormsModule,
    MatTooltipModule,
    MatDialogModule,
    MatExpansionModule,
    MatRippleModule,
    MatSnackBarModule,
    MatListModule,
    MatSelectModule,
    MatCheckboxModule,
    MatListModule,
    MatToolbarModule,
    MatTabsModule,
    MatTableModule,
    MatPaginatorModule
  ],
  exports: [
    MatCardModule,
    MatButtonModule,
    MatGridListModule,
    MatMenuModule,
    MatIconModule,
    MatSidenavModule,
    MatSliderModule,
    MatAutocompleteModule,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    MatExpansionModule,
    FormsModule,
    ReactiveFormsModule,
    MatTooltipModule,
    MatDialogModule,
    MatExpansionModule,
    MatRippleModule,
    MatSnackBarModule,
    MatListModule,
    MatSelectModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatTabsModule,
    MatTableModule,
    MatPaginatorModule
  ]
})
export class MaterialModule {}
